name: 'deploy'
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          yarn && yarn build
      - uses: 0xKrauser/bundlr-action@v1
        with:
          path: './dist'
          private-key: ${{ secrets.PK }}
          bundlr-endpoint: 'http://node1.bundlr.network'

